name: CI

on: push

env:
  MIX_ENV: test
  OTP_VERSION_SPEC: "23.x"
  ELIXIR_VERSION_SPEC: "1.10.x"

jobs:
  format:
    name: "Check Formatted"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: doughsay/setup-elixir@1148b8ff819424a2efa48ff89af3ccc114c1fc39
        id: setup
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
      - name: Check formatted
        run: |
          echo ${{ steps.setup.outputs['otp-version'] }}
          echo ${{ steps.setup.outputs['elixir-version'] }}
          mix format --check-formatted

  compile:
    name: Compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: doughsay/setup-elixir@1148b8ff819424a2efa48ff89af3ccc114c1fc39
        id: setup
        with:
          otp-version: ${{ env.OTP_VERSION_SPEC }}
          elixir-version: ${{ env.ELIXIR_VERSION_SPEC }}
      - uses: actions/cache@v2.1.0
        id: cache_deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-
      - uses: actions/cache@v2.1.0
        id: cache_build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-${{ hashFiles('{lib/**/*.ex,test/**/*.ex,mix.lock}') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-
      - name: Install dependencies
        if: steps.cache_deps.outputs['cache-hit'] != 'true'
        run: mix deps.get
      - name: Compile
        if: steps.cache_build.outputs['cache-hit'] != 'true'
        run: mix compile --warnings-as-errors

  test:
    name: Tests

    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: doughsay/setup-elixir@1148b8ff819424a2efa48ff89af3ccc114c1fc39
        id: setup
        with:
          otp-version: "23.x"
          elixir-version: "1.10.x"
      - uses: actions/cache@v2.1.0
        id: cache_deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v2.1.0
        id: cache_build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-${{ hashFiles('{lib/**/*.ex,test/**/*.ex,mix.lock}') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-
      - name: Install dependencies
        if: steps.cache_deps.outputs['cache-hit'] != 'true'
        run: mix deps.get
      - name: Compile
        if: steps.cache_build.outputs['cache-hit'] != 'true'
        run: mix compile
      - name: Run tests
        run: mix coveralls.json
      - uses: codecov/codecov-action@v1
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          fail_ci_if_error: true

  credo:
    name: Credo

    needs: compile

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: doughsay/setup-elixir@1148b8ff819424a2efa48ff89af3ccc114c1fc39
        id: setup
        with:
          otp-version: "23.x"
          elixir-version: "1.10.x"
      - uses: actions/cache@v2.1.0
        id: cache_deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v2.1.0
        id: cache_build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-${{ hashFiles('{lib/**/*.ex,test/**/*.ex,mix.lock}') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-
      - name: Install dependencies
        if: steps.cache_deps.outputs['cache-hit'] != 'true'
        run: mix deps.get
      - name: Compile
        if: steps.cache_build.outputs['cache-hit'] != 'true'
        run: mix compile
      - name: Run credo
        run: mix credo --strict

  dialyzer:
    name: Dialyzer

    runs-on: ubuntu-latest

    env:
      MIX_ENV: dev

    steps:
      - uses: actions/checkout@v2
      - uses: doughsay/setup-elixir@1148b8ff819424a2efa48ff89af3ccc114c1fc39
        id: setup
        with:
          otp-version: "23.x"
          elixir-version: "1.10.x"
      - uses: actions/cache@v2.1.0
        id: cache_deps
        with:
          path: deps
          key: ${{ runner.os }}-${{ hashFiles('mix.lock') }}
      - uses: actions/cache@v2.1.0
        id: cache_build
        with:
          path: _build
          key: ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-${{ hashFiles('{lib/**/*.ex,test/**/*.ex,mix.lock}') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.MIX_ENV }}-${{ steps.setup.outputs['otp-version'] }}-${{ steps.setup.outputs['elixir-version'] }}-
      - name: Install dependencies
        if: steps.cache_deps.outputs['cache-hit'] != 'true'
        run: mix deps.get
      - name: Compile
        if: steps.cache_build.outputs['cache-hit'] != 'true'
        run: mix compile
      - name: Run dialyzer
        run: mix dialyzer
